#!/bin/sh

# copyright: B1 Systems GmbH <info@b1-systems.de>, 2018
# license:   GPLv3+, http://www.gnu.org/licenses/gpl-3.0.html

echo "Hi ${USER}! You've successfully authenticated,"
echo "but I don't provide interactive shell access."
exit 128
