# copyright: B1 Systems GmbH <info@b1-systems.de>, 2018
# license:   GPLv3+, http://www.gnu.org/licenses/gpl-3.0.html

moduledir 'modules'

mod 'puppetlabs-stdlib'

mod 'puppetlabs-ntp', '4.1.2'

mod 'puppetlabs-puppetdb', :latest

mod 'apache',
  :git => 'https://github.com/puppetlabs/puppetlabs-apache',
  :tag => '0.9.0'

mod 'test42', :local => true
